---

- name: set_fact <|> Build host to network mapping
  set_fact:
    hosts_file_hosts_by_first_octets: "{{ hostvars | bluebanquise.infrastructure.hosts_by_first_octets(groups['all'], networks) }}"
  delegate_to: localhost
  delegate_facts: true
  run_once: true
  tags:
    - template

- name: template <|> Generate /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - template
